### ISSUE TITLE
Handle int64

### ISSUE THREAD

**Issue by mcollina** [mcollina/msgpack5#17]
Currently we do not support int64. I think we should do that using https://github.com/broofa/node-int64.

Any opinions?

**Comment by planetbeing** [comment]
(First, thanks for your work on this project!)

I need int64 support and I think using that library is fine. The current way that msgpack5 encodes int64 is not to spec (as of 2.0.0):

    > msgpack.encode(0x1234567812345600)
    <Buffer cf 24 68 ac 00 12 34 56 78>

Expected:

    > msgpack.encode(0x1234567812345600)
    <Buffer cf 12 34 56 78 12 34 56 00>

I ran into this problem trying to interoperate this library with https://github.com/msgpack/msgpack-javascript (probably problematic anyway besides this problem due to how dated the other project is).

I think even if approximate 64-bit values were used, the encoding of the approximate value should match that of the specification.

**Comment by mcollina** [comment]
Thanks for reporting! Can you please send a PR to address this problem?

**Comment by mtburt** [comment]
Wanted to check in and see if there is a fix for this.  I found the same problem and fixed the byte order and offset issue but not using the library, just the javascript int representation.  If you think the fix using the library is coming I'll wait for it, otherwise I'm happy to submit my fix.

**Comment by mcollina** [comment]
This should be already released.
Il giorno gio 7 mag 2015 alle 01:31 mtburt <notifications@github.com> ha
scritto:

**Comment by rochdev** [comment]
@mcollina Just tried using this library for objects containing int64 and it doesn't seem to work.

For example:

```js
console.log(encode(0xffffffffffffffff))
<Buffer cb 43 f0 00 00 00 00 00 00>
```

I would expect the buffer to be:

```
<Buffer cb ff ff ff ff ff ff ff ff>
```

**Comment by rochdev** [comment]
If you reopen this issue I could submit a PR to add support for `node-int64`

**Comment by mcollina** [comment]
Feel free to open an new issue, this one is very old.

**Comment by rochdev** [comment]
Opened #61
